version: "2"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/build/mysql/schema:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3367:3306"
